### ISSUE TITLE
plugin assets (javascript) should not be loaded on any page!

### ISSUE THREAD

**Issue by tofi86** [schmidt/redmine_zxcvbn#1]
The plugin javascript assets should not be loaded on any page, but only on the _edit password_ page...

**Comment by schmidt** [comment]
Hi Tobias,

Since any plugin can add password fields to the Redmine UI, we've decided to always load a small part of the JS code - basically that part, that does the integration. The huge part - the zxcvbn library itself - is only loaded if needed.

See 

* https://github.com/schmidt/redmine_zxcvbn/blob/8cb0cd936ec7dcb2d4ced1c7dba41c0a835edb95/assets/javascripts/redmine_zxcvbn.js#L12-L17
* https://github.com/schmidt/redmine_zxcvbn/blob/8cb0cd936ec7dcb2d4ced1c7dba41c0a835edb95/assets/javascripts/redmine_zxcvbn.js#L28

Does this answer your request?

**Comment by tofi86** [comment]
That sounds reasonable! Good idea!

I'm fine with that then... ;-)
